# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web & Democracy
author: RISD Graphic Design Elective, Fall 2018
email: jcaserta@risd.edu
description: Is the Internet making the world a better place or is it simply remaking the world – peacefully transferring capital from 20th century corporations to 21st century ones? If the digital space is becoming primary, then who is tending to the systems of self-government, defined so articulately in the age of Enlightenment?

This Web research elective asks students to design tools that further the public’s interest online. Can the Web – designed as an open and free medium – reinvigorate our investment in public space and the public good? Students will work together to engage politicians, non-profits, and fellow citizens in the pursuit of these questions.

Assignments will range from Web tools that serve democracy to civic fundraising to information dissemination. Class deliverables will be a combination of prototypes, presentations and coded mini-sites. Students will develop the parameters for the final project and work in teams. Outside collaborators and readings will enrich the conversation and the work. No previous web experience required, but Web Programming workshop strongly encouraged.


baseurl: "" # the subpath of your site, e.g. /blog
url: http://wd.risd.gd the base hostname & protocol for your site
canonical_url: http://wd.risd.gd # the canonical base hostname to use for titles and permalinks
markdown: kramdown
exclude: [package.json, package-lock.json, node_modules/]
